/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";

import type { Initializable } from "../Initializable";

export class Initializable__factory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<Initializable> {
    return super.deploy(overrides || {}) as Promise<Initializable>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): Initializable {
    return super.attach(address) as Initializable;
  }
  connect(signer: Signer): Initializable__factory {
    return super.connect(signer) as Initializable__factory;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): Initializable {
    return new Contract(address, _abi, signerOrProvider) as Initializable;
  }
}

const _abi = [
  {
    constant: true,
    inputs: [],
    name: "getInitialized",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
];

const _bytecode =
  "0x60806040526000805460ff19169055348015601957600080fd5b506085806100286000396000f3fe6080604052348015600f57600080fd5b506004361060285760003560e01c8063ee89dab414602d575b600080fd5b60336047565b604080519115158252519081900360200190f35b60005460ff169056fea265627a7a72315820271f45c5aedbc6b3b13a26fda527e5ffa02aabe7377a7ed0154d5eb5a844527f64736f6c634300050f0032";
