/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { ITurboShareTokenFactory } from "../ITurboShareTokenFactory";

export class ITurboShareTokenFactory__factory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ITurboShareTokenFactory {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as ITurboShareTokenFactory;
  }
}

const _abi = [
  {
    constant: false,
    inputs: [
      {
        internalType: "bytes32[]",
        name: "_names",
        type: "bytes32[]",
      },
      {
        internalType: "string[]",
        name: "_symbols",
        type: "string[]",
      },
    ],
    name: "createShareTokens",
    outputs: [
      {
        internalType: "contract ITurboShareToken[]",
        name: "tokens",
        type: "address[]",
      },
    ],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
];
