/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { ITyped } from "../ITyped";

export class ITyped__factory {
  static connect(address: string, signerOrProvider: Signer | Provider): ITyped {
    return new Contract(address, _abi, signerOrProvider) as ITyped;
  }
}

const _abi = [
  {
    constant: true,
    inputs: [],
    name: "getTypeName",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
];
