/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface IArbiterInterface extends ethers.utils.Interface {
  functions: {
    "getTurboResolution(uint256)": FunctionFragment;
    "onTurboCreated(uint256,string[],bytes32[],uint256,bytes)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "getTurboResolution",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "onTurboCreated",
    values: [BigNumberish, string[], BytesLike[], BigNumberish, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "getTurboResolution",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "onTurboCreated",
    data: BytesLike
  ): Result;

  events: {};
}

export class IArbiter extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: IArbiterInterface;

  functions: {
    getTurboResolution(
      _id: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "getTurboResolution(uint256)"(
      _id: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    onTurboCreated(
      _id: BigNumberish,
      _outcomeSymbols: string[],
      _outcomeNames: BytesLike[],
      _numTicks: BigNumberish,
      _arbiterConfiguration: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "onTurboCreated(uint256,string[],bytes32[],uint256,bytes)"(
      _id: BigNumberish,
      _outcomeSymbols: string[],
      _outcomeNames: BytesLike[],
      _numTicks: BigNumberish,
      _arbiterConfiguration: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  getTurboResolution(
    _id: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "getTurboResolution(uint256)"(
    _id: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  onTurboCreated(
    _id: BigNumberish,
    _outcomeSymbols: string[],
    _outcomeNames: BytesLike[],
    _numTicks: BigNumberish,
    _arbiterConfiguration: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "onTurboCreated(uint256,string[],bytes32[],uint256,bytes)"(
    _id: BigNumberish,
    _outcomeSymbols: string[],
    _outcomeNames: BytesLike[],
    _numTicks: BigNumberish,
    _arbiterConfiguration: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    getTurboResolution(
      _id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber[]>;

    "getTurboResolution(uint256)"(
      _id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber[]>;

    onTurboCreated(
      _id: BigNumberish,
      _outcomeSymbols: string[],
      _outcomeNames: BytesLike[],
      _numTicks: BigNumberish,
      _arbiterConfiguration: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    "onTurboCreated(uint256,string[],bytes32[],uint256,bytes)"(
      _id: BigNumberish,
      _outcomeSymbols: string[],
      _outcomeNames: BytesLike[],
      _numTicks: BigNumberish,
      _arbiterConfiguration: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    getTurboResolution(
      _id: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "getTurboResolution(uint256)"(
      _id: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    onTurboCreated(
      _id: BigNumberish,
      _outcomeSymbols: string[],
      _outcomeNames: BytesLike[],
      _numTicks: BigNumberish,
      _arbiterConfiguration: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "onTurboCreated(uint256,string[],bytes32[],uint256,bytes)"(
      _id: BigNumberish,
      _outcomeSymbols: string[],
      _outcomeNames: BytesLike[],
      _numTicks: BigNumberish,
      _arbiterConfiguration: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getTurboResolution(
      _id: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "getTurboResolution(uint256)"(
      _id: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    onTurboCreated(
      _id: BigNumberish,
      _outcomeSymbols: string[],
      _outcomeNames: BytesLike[],
      _numTicks: BigNumberish,
      _arbiterConfiguration: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "onTurboCreated(uint256,string[],bytes32[],uint256,bytes)"(
      _id: BigNumberish,
      _outcomeSymbols: string[],
      _outcomeNames: BytesLike[],
      _numTicks: BigNumberish,
      _arbiterConfiguration: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
